// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddWindowContextArgs {
    pub id: String,
    pub name: String,
    pub matcher_app_name: String,
    pub matcher_title_pattern: Option<String>,
    pub matcher_bundle_id: Option<String>,
    pub command_mode: String,
    pub dictionary_mode: String,
    pub command_ids_json: String,
    pub dictionary_entry_ids_json: String,
    pub enabled: bool,
    pub priority: i32,
}

impl From<AddWindowContextArgs> for super::Reducer {
    fn from(args: AddWindowContextArgs) -> Self {
        Self::AddWindowContext {
            id: args.id,
            name: args.name,
            matcher_app_name: args.matcher_app_name,
            matcher_title_pattern: args.matcher_title_pattern,
            matcher_bundle_id: args.matcher_bundle_id,
            command_mode: args.command_mode,
            dictionary_mode: args.dictionary_mode,
            command_ids_json: args.command_ids_json,
            dictionary_entry_ids_json: args.dictionary_entry_ids_json,
            enabled: args.enabled,
            priority: args.priority,
        }
    }
}

impl __sdk::InModule for AddWindowContextArgs {
    type Module = super::RemoteModule;
}

pub struct AddWindowContextCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_window_context`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_window_context {
    /// Request that the remote module invoke the reducer `add_window_context` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_window_context`] callbacks.
    fn add_window_context(
        &self,
        id: String,
        name: String,
        matcher_app_name: String,
        matcher_title_pattern: Option<String>,
        matcher_bundle_id: Option<String>,
        command_mode: String,
        dictionary_mode: String,
        command_ids_json: String,
        dictionary_entry_ids_json: String,
        enabled: bool,
        priority: i32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_window_context`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddWindowContextCallbackId`] can be passed to [`Self::remove_on_add_window_context`]
    /// to cancel the callback.
    fn on_add_window_context(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &Option<String>,
                &Option<String>,
                &String,
                &String,
                &String,
                &String,
                &bool,
                &i32,
            ) + Send
            + 'static,
    ) -> AddWindowContextCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_window_context`],
    /// causing it not to run in the future.
    fn remove_on_add_window_context(&self, callback: AddWindowContextCallbackId);
}

impl add_window_context for super::RemoteReducers {
    fn add_window_context(
        &self,
        id: String,
        name: String,
        matcher_app_name: String,
        matcher_title_pattern: Option<String>,
        matcher_bundle_id: Option<String>,
        command_mode: String,
        dictionary_mode: String,
        command_ids_json: String,
        dictionary_entry_ids_json: String,
        enabled: bool,
        priority: i32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_window_context",
            AddWindowContextArgs {
                id,
                name,
                matcher_app_name,
                matcher_title_pattern,
                matcher_bundle_id,
                command_mode,
                dictionary_mode,
                command_ids_json,
                dictionary_entry_ids_json,
                enabled,
                priority,
            },
        )
    }
    fn on_add_window_context(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &Option<String>,
                &Option<String>,
                &String,
                &String,
                &String,
                &String,
                &bool,
                &i32,
            ) + Send
            + 'static,
    ) -> AddWindowContextCallbackId {
        AddWindowContextCallbackId(self.imp.on_reducer(
            "add_window_context",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddWindowContext {
                                    id,
                                    name,
                                    matcher_app_name,
                                    matcher_title_pattern,
                                    matcher_bundle_id,
                                    command_mode,
                                    dictionary_mode,
                                    command_ids_json,
                                    dictionary_entry_ids_json,
                                    enabled,
                                    priority,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    id,
                    name,
                    matcher_app_name,
                    matcher_title_pattern,
                    matcher_bundle_id,
                    command_mode,
                    dictionary_mode,
                    command_ids_json,
                    dictionary_entry_ids_json,
                    enabled,
                    priority,
                )
            }),
        ))
    }
    fn remove_on_add_window_context(&self, callback: AddWindowContextCallbackId) {
        self.imp.remove_on_reducer("add_window_context", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_window_context`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_window_context {
    /// Set the call-reducer flags for the reducer `add_window_context` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_window_context(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_window_context for super::SetReducerFlags {
    fn add_window_context(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_window_context", flags);
    }
}
