// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddVoiceCommandArgs {
    pub id: String,
    pub trigger: String,
    pub action_type: String,
    pub parameters_json: String,
    pub enabled: bool,
}

impl From<AddVoiceCommandArgs> for super::Reducer {
    fn from(args: AddVoiceCommandArgs) -> Self {
        Self::AddVoiceCommand {
            id: args.id,
            trigger: args.trigger,
            action_type: args.action_type,
            parameters_json: args.parameters_json,
            enabled: args.enabled,
        }
    }
}

impl __sdk::InModule for AddVoiceCommandArgs {
    type Module = super::RemoteModule;
}

pub struct AddVoiceCommandCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_voice_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_voice_command {
    /// Request that the remote module invoke the reducer `add_voice_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_voice_command`] callbacks.
    fn add_voice_command(
        &self,
        id: String,
        trigger: String,
        action_type: String,
        parameters_json: String,
        enabled: bool,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_voice_command`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddVoiceCommandCallbackId`] can be passed to [`Self::remove_on_add_voice_command`]
    /// to cancel the callback.
    fn on_add_voice_command(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &bool)
            + Send
            + 'static,
    ) -> AddVoiceCommandCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_voice_command`],
    /// causing it not to run in the future.
    fn remove_on_add_voice_command(&self, callback: AddVoiceCommandCallbackId);
}

impl add_voice_command for super::RemoteReducers {
    fn add_voice_command(
        &self,
        id: String,
        trigger: String,
        action_type: String,
        parameters_json: String,
        enabled: bool,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_voice_command",
            AddVoiceCommandArgs {
                id,
                trigger,
                action_type,
                parameters_json,
                enabled,
            },
        )
    }
    fn on_add_voice_command(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &bool)
            + Send
            + 'static,
    ) -> AddVoiceCommandCallbackId {
        AddVoiceCommandCallbackId(self.imp.on_reducer(
            "add_voice_command",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddVoiceCommand {
                                    id,
                                    trigger,
                                    action_type,
                                    parameters_json,
                                    enabled,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, trigger, action_type, parameters_json, enabled)
            }),
        ))
    }
    fn remove_on_add_voice_command(&self, callback: AddVoiceCommandCallbackId) {
        self.imp.remove_on_reducer("add_voice_command", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_voice_command`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_voice_command {
    /// Set the call-reducer flags for the reducer `add_voice_command` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_voice_command(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_voice_command for super::SetReducerFlags {
    fn add_voice_command(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_voice_command", flags);
    }
}
