// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddRecordingArgs {
    pub id: String,
    pub file_path: String,
    pub duration_secs: f64,
    pub sample_count: u64,
    pub stop_reason: Option<String>,
}

impl From<AddRecordingArgs> for super::Reducer {
    fn from(args: AddRecordingArgs) -> Self {
        Self::AddRecording {
            id: args.id,
            file_path: args.file_path,
            duration_secs: args.duration_secs,
            sample_count: args.sample_count,
            stop_reason: args.stop_reason,
        }
    }
}

impl __sdk::InModule for AddRecordingArgs {
    type Module = super::RemoteModule;
}

pub struct AddRecordingCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_recording`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_recording {
    /// Request that the remote module invoke the reducer `add_recording` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_recording`] callbacks.
    fn add_recording(
        &self,
        id: String,
        file_path: String,
        duration_secs: f64,
        sample_count: u64,
        stop_reason: Option<String>,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_recording`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddRecordingCallbackId`] can be passed to [`Self::remove_on_add_recording`]
    /// to cancel the callback.
    fn on_add_recording(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &f64, &u64, &Option<String>)
            + Send
            + 'static,
    ) -> AddRecordingCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_recording`],
    /// causing it not to run in the future.
    fn remove_on_add_recording(&self, callback: AddRecordingCallbackId);
}

impl add_recording for super::RemoteReducers {
    fn add_recording(
        &self,
        id: String,
        file_path: String,
        duration_secs: f64,
        sample_count: u64,
        stop_reason: Option<String>,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_recording",
            AddRecordingArgs {
                id,
                file_path,
                duration_secs,
                sample_count,
                stop_reason,
            },
        )
    }
    fn on_add_recording(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &f64, &u64, &Option<String>)
            + Send
            + 'static,
    ) -> AddRecordingCallbackId {
        AddRecordingCallbackId(self.imp.on_reducer(
            "add_recording",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddRecording {
                                    id,
                                    file_path,
                                    duration_secs,
                                    sample_count,
                                    stop_reason,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, file_path, duration_secs, sample_count, stop_reason)
            }),
        ))
    }
    fn remove_on_add_recording(&self, callback: AddRecordingCallbackId) {
        self.imp.remove_on_reducer("add_recording", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_recording`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_recording {
    /// Set the call-reducer flags for the reducer `add_recording` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_recording(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_recording for super::SetReducerFlags {
    fn add_recording(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_recording", flags);
    }
}
