// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddTranscriptionArgs {
    pub id: String,
    pub recording_id: String,
    pub text: String,
    pub language: Option<String>,
    pub model_version: String,
    pub duration_ms: u64,
}

impl From<AddTranscriptionArgs> for super::Reducer {
    fn from(args: AddTranscriptionArgs) -> Self {
        Self::AddTranscription {
            id: args.id,
            recording_id: args.recording_id,
            text: args.text,
            language: args.language,
            model_version: args.model_version,
            duration_ms: args.duration_ms,
        }
    }
}

impl __sdk::InModule for AddTranscriptionArgs {
    type Module = super::RemoteModule;
}

pub struct AddTranscriptionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_transcription`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_transcription {
    /// Request that the remote module invoke the reducer `add_transcription` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_transcription`] callbacks.
    fn add_transcription(
        &self,
        id: String,
        recording_id: String,
        text: String,
        language: Option<String>,
        model_version: String,
        duration_ms: u64,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_transcription`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddTranscriptionCallbackId`] can be passed to [`Self::remove_on_add_transcription`]
    /// to cancel the callback.
    fn on_add_transcription(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &Option<String>,
                &String,
                &u64,
            ) + Send
            + 'static,
    ) -> AddTranscriptionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_transcription`],
    /// causing it not to run in the future.
    fn remove_on_add_transcription(&self, callback: AddTranscriptionCallbackId);
}

impl add_transcription for super::RemoteReducers {
    fn add_transcription(
        &self,
        id: String,
        recording_id: String,
        text: String,
        language: Option<String>,
        model_version: String,
        duration_ms: u64,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_transcription",
            AddTranscriptionArgs {
                id,
                recording_id,
                text,
                language,
                model_version,
                duration_ms,
            },
        )
    }
    fn on_add_transcription(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &Option<String>,
                &String,
                &u64,
            ) + Send
            + 'static,
    ) -> AddTranscriptionCallbackId {
        AddTranscriptionCallbackId(self.imp.on_reducer(
            "add_transcription",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddTranscription {
                                    id,
                                    recording_id,
                                    text,
                                    language,
                                    model_version,
                                    duration_ms,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    id,
                    recording_id,
                    text,
                    language,
                    model_version,
                    duration_ms,
                )
            }),
        ))
    }
    fn remove_on_add_transcription(&self, callback: AddTranscriptionCallbackId) {
        self.imp.remove_on_reducer("add_transcription", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_transcription`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_transcription {
    /// Set the call-reducer flags for the reducer `add_transcription` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_transcription(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_transcription for super::SetReducerFlags {
    fn add_transcription(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_transcription", flags);
    }
}
