// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteRecordingArgs {
    pub id: String,
}

impl From<DeleteRecordingArgs> for super::Reducer {
    fn from(args: DeleteRecordingArgs) -> Self {
        Self::DeleteRecording { id: args.id }
    }
}

impl __sdk::InModule for DeleteRecordingArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteRecordingCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_recording`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_recording {
    /// Request that the remote module invoke the reducer `delete_recording` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_recording`] callbacks.
    fn delete_recording(&self, id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_recording`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteRecordingCallbackId`] can be passed to [`Self::remove_on_delete_recording`]
    /// to cancel the callback.
    fn on_delete_recording(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> DeleteRecordingCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_recording`],
    /// causing it not to run in the future.
    fn remove_on_delete_recording(&self, callback: DeleteRecordingCallbackId);
}

impl delete_recording for super::RemoteReducers {
    fn delete_recording(&self, id: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("delete_recording", DeleteRecordingArgs { id })
    }
    fn on_delete_recording(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> DeleteRecordingCallbackId {
        DeleteRecordingCallbackId(self.imp.on_reducer(
            "delete_recording",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteRecording { id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id)
            }),
        ))
    }
    fn remove_on_delete_recording(&self, callback: DeleteRecordingCallbackId) {
        self.imp.remove_on_reducer("delete_recording", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_recording`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_recording {
    /// Set the call-reducer flags for the reducer `delete_recording` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_recording(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_recording for super::SetReducerFlags {
    fn delete_recording(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_recording", flags);
    }
}
