// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteRecordingByPathArgs {
    pub file_path: String,
}

impl From<DeleteRecordingByPathArgs> for super::Reducer {
    fn from(args: DeleteRecordingByPathArgs) -> Self {
        Self::DeleteRecordingByPath {
            file_path: args.file_path,
        }
    }
}

impl __sdk::InModule for DeleteRecordingByPathArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteRecordingByPathCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_recording_by_path`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_recording_by_path {
    /// Request that the remote module invoke the reducer `delete_recording_by_path` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_recording_by_path`] callbacks.
    fn delete_recording_by_path(&self, file_path: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_recording_by_path`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteRecordingByPathCallbackId`] can be passed to [`Self::remove_on_delete_recording_by_path`]
    /// to cancel the callback.
    fn on_delete_recording_by_path(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> DeleteRecordingByPathCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_recording_by_path`],
    /// causing it not to run in the future.
    fn remove_on_delete_recording_by_path(&self, callback: DeleteRecordingByPathCallbackId);
}

impl delete_recording_by_path for super::RemoteReducers {
    fn delete_recording_by_path(&self, file_path: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "delete_recording_by_path",
            DeleteRecordingByPathArgs { file_path },
        )
    }
    fn on_delete_recording_by_path(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> DeleteRecordingByPathCallbackId {
        DeleteRecordingByPathCallbackId(self.imp.on_reducer(
            "delete_recording_by_path",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteRecordingByPath { file_path },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, file_path)
            }),
        ))
    }
    fn remove_on_delete_recording_by_path(&self, callback: DeleteRecordingByPathCallbackId) {
        self.imp
            .remove_on_reducer("delete_recording_by_path", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_recording_by_path`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_recording_by_path {
    /// Set the call-reducer flags for the reducer `delete_recording_by_path` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_recording_by_path(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_recording_by_path for super::SetReducerFlags {
    fn delete_recording_by_path(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("delete_recording_by_path", flags);
    }
}
