// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dictionary_entry_type::DictionaryEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dictionary_entry`.
///
/// Obtain a handle from the [`DictionaryEntryTableAccess::dictionary_entry`] method on [`super::RemoteTables`],
/// like `ctx.db.dictionary_entry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dictionary_entry().on_insert(...)`.
pub struct DictionaryEntryTableHandle<'ctx> {
    imp: __sdk::TableHandle<DictionaryEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dictionary_entry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DictionaryEntryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DictionaryEntryTableHandle`], which mediates access to the table `dictionary_entry`.
    fn dictionary_entry(&self) -> DictionaryEntryTableHandle<'_>;
}

impl DictionaryEntryTableAccess for super::RemoteTables {
    fn dictionary_entry(&self) -> DictionaryEntryTableHandle<'_> {
        DictionaryEntryTableHandle {
            imp: self.imp.get_table::<DictionaryEntry>("dictionary_entry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DictionaryEntryInsertCallbackId(__sdk::CallbackId);
pub struct DictionaryEntryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DictionaryEntryTableHandle<'ctx> {
    type Row = DictionaryEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DictionaryEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DictionaryEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DictionaryEntryInsertCallbackId {
        DictionaryEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DictionaryEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DictionaryEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DictionaryEntryDeleteCallbackId {
        DictionaryEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DictionaryEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DictionaryEntry>("dictionary_entry");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("trigger", |row| &row.trigger);
}
pub struct DictionaryEntryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DictionaryEntryTableHandle<'ctx> {
    type UpdateCallbackId = DictionaryEntryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DictionaryEntryUpdateCallbackId {
        DictionaryEntryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DictionaryEntryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DictionaryEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DictionaryEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `dictionary_entry`,
/// which allows point queries on the field of the same name
/// via the [`DictionaryEntryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dictionary_entry().id().find(...)`.
pub struct DictionaryEntryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DictionaryEntry, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DictionaryEntryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dictionary_entry`.
    pub fn id(&self) -> DictionaryEntryIdUnique<'ctx> {
        DictionaryEntryIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DictionaryEntryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<DictionaryEntry> {
        self.imp.find(col_val)
    }
}

/// Access to the `trigger` unique index on the table `dictionary_entry`,
/// which allows point queries on the field of the same name
/// via the [`DictionaryEntryTriggerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dictionary_entry().trigger().find(...)`.
pub struct DictionaryEntryTriggerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DictionaryEntry, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DictionaryEntryTableHandle<'ctx> {
    /// Get a handle on the `trigger` unique index on the table `dictionary_entry`.
    pub fn trigger(&self) -> DictionaryEntryTriggerUnique<'ctx> {
        DictionaryEntryTriggerUnique {
            imp: self.imp.get_unique_constraint::<String>("trigger"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DictionaryEntryTriggerUnique<'ctx> {
    /// Find the subscribed row whose `trigger` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<DictionaryEntry> {
        self.imp.find(col_val)
    }
}
