// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DictionaryEntry {
    pub id: String,
    pub trigger: String,
    pub expansion: String,
    pub suffix: Option<String>,
    pub auto_enter: bool,
    pub disable_suffix: bool,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for DictionaryEntry {
    type Module = super::RemoteModule;
}
