// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::recording_type::Recording;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `recording`.
///
/// Obtain a handle from the [`RecordingTableAccess::recording`] method on [`super::RemoteTables`],
/// like `ctx.db.recording()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recording().on_insert(...)`.
pub struct RecordingTableHandle<'ctx> {
    imp: __sdk::TableHandle<Recording>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `recording`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RecordingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RecordingTableHandle`], which mediates access to the table `recording`.
    fn recording(&self) -> RecordingTableHandle<'_>;
}

impl RecordingTableAccess for super::RemoteTables {
    fn recording(&self) -> RecordingTableHandle<'_> {
        RecordingTableHandle {
            imp: self.imp.get_table::<Recording>("recording"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RecordingInsertCallbackId(__sdk::CallbackId);
pub struct RecordingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RecordingTableHandle<'ctx> {
    type Row = Recording;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Recording> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RecordingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecordingInsertCallbackId {
        RecordingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RecordingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RecordingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecordingDeleteCallbackId {
        RecordingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RecordingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Recording>("recording");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("file_path", |row| &row.file_path);
}
pub struct RecordingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RecordingTableHandle<'ctx> {
    type UpdateCallbackId = RecordingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RecordingUpdateCallbackId {
        RecordingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RecordingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Recording>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Recording>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `recording`,
/// which allows point queries on the field of the same name
/// via the [`RecordingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recording().id().find(...)`.
pub struct RecordingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Recording, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RecordingTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `recording`.
    pub fn id(&self) -> RecordingIdUnique<'ctx> {
        RecordingIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RecordingIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Recording> {
        self.imp.find(col_val)
    }
}

/// Access to the `file_path` unique index on the table `recording`,
/// which allows point queries on the field of the same name
/// via the [`RecordingFilePathUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recording().file_path().find(...)`.
pub struct RecordingFilePathUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Recording, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RecordingTableHandle<'ctx> {
    /// Get a handle on the `file_path` unique index on the table `recording`.
    pub fn file_path(&self) -> RecordingFilePathUnique<'ctx> {
        RecordingFilePathUnique {
            imp: self.imp.get_unique_constraint::<String>("file_path"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RecordingFilePathUnique<'ctx> {
    /// Find the subscribed row whose `file_path` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Recording> {
        self.imp.find(col_val)
    }
}
