// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transcription_type::Transcription;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `transcription`.
///
/// Obtain a handle from the [`TranscriptionTableAccess::transcription`] method on [`super::RemoteTables`],
/// like `ctx.db.transcription()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transcription().on_insert(...)`.
pub struct TranscriptionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Transcription>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `transcription`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TranscriptionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TranscriptionTableHandle`], which mediates access to the table `transcription`.
    fn transcription(&self) -> TranscriptionTableHandle<'_>;
}

impl TranscriptionTableAccess for super::RemoteTables {
    fn transcription(&self) -> TranscriptionTableHandle<'_> {
        TranscriptionTableHandle {
            imp: self.imp.get_table::<Transcription>("transcription"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TranscriptionInsertCallbackId(__sdk::CallbackId);
pub struct TranscriptionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TranscriptionTableHandle<'ctx> {
    type Row = Transcription;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Transcription> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TranscriptionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TranscriptionInsertCallbackId {
        TranscriptionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TranscriptionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TranscriptionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TranscriptionDeleteCallbackId {
        TranscriptionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TranscriptionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Transcription>("transcription");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct TranscriptionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TranscriptionTableHandle<'ctx> {
    type UpdateCallbackId = TranscriptionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TranscriptionUpdateCallbackId {
        TranscriptionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TranscriptionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Transcription>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Transcription>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `transcription`,
/// which allows point queries on the field of the same name
/// via the [`TranscriptionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transcription().id().find(...)`.
pub struct TranscriptionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Transcription, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TranscriptionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `transcription`.
    pub fn id(&self) -> TranscriptionIdUnique<'ctx> {
        TranscriptionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TranscriptionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Transcription> {
        self.imp.find(col_val)
    }
}
