// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::voice_command_type::VoiceCommand;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `voice_command`.
///
/// Obtain a handle from the [`VoiceCommandTableAccess::voice_command`] method on [`super::RemoteTables`],
/// like `ctx.db.voice_command()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voice_command().on_insert(...)`.
pub struct VoiceCommandTableHandle<'ctx> {
    imp: __sdk::TableHandle<VoiceCommand>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `voice_command`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VoiceCommandTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VoiceCommandTableHandle`], which mediates access to the table `voice_command`.
    fn voice_command(&self) -> VoiceCommandTableHandle<'_>;
}

impl VoiceCommandTableAccess for super::RemoteTables {
    fn voice_command(&self) -> VoiceCommandTableHandle<'_> {
        VoiceCommandTableHandle {
            imp: self.imp.get_table::<VoiceCommand>("voice_command"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VoiceCommandInsertCallbackId(__sdk::CallbackId);
pub struct VoiceCommandDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VoiceCommandTableHandle<'ctx> {
    type Row = VoiceCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VoiceCommand> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VoiceCommandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoiceCommandInsertCallbackId {
        VoiceCommandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VoiceCommandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VoiceCommandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoiceCommandDeleteCallbackId {
        VoiceCommandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VoiceCommandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VoiceCommand>("voice_command");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("trigger", |row| &row.trigger);
}
pub struct VoiceCommandUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VoiceCommandTableHandle<'ctx> {
    type UpdateCallbackId = VoiceCommandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VoiceCommandUpdateCallbackId {
        VoiceCommandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VoiceCommandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<VoiceCommand>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VoiceCommand>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `voice_command`,
/// which allows point queries on the field of the same name
/// via the [`VoiceCommandIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voice_command().id().find(...)`.
pub struct VoiceCommandIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VoiceCommand, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VoiceCommandTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `voice_command`.
    pub fn id(&self) -> VoiceCommandIdUnique<'ctx> {
        VoiceCommandIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VoiceCommandIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<VoiceCommand> {
        self.imp.find(col_val)
    }
}

/// Access to the `trigger` unique index on the table `voice_command`,
/// which allows point queries on the field of the same name
/// via the [`VoiceCommandTriggerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voice_command().trigger().find(...)`.
pub struct VoiceCommandTriggerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VoiceCommand, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VoiceCommandTableHandle<'ctx> {
    /// Get a handle on the `trigger` unique index on the table `voice_command`.
    pub fn trigger(&self) -> VoiceCommandTriggerUnique<'ctx> {
        VoiceCommandTriggerUnique {
            imp: self.imp.get_unique_constraint::<String>("trigger"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VoiceCommandTriggerUnique<'ctx> {
    /// Find the subscribed row whose `trigger` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<VoiceCommand> {
        self.imp.find(col_val)
    }
}
