// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WindowContext {
    pub id: String,
    pub name: String,
    pub matcher_app_name: String,
    pub matcher_title_pattern: Option<String>,
    pub matcher_bundle_id: Option<String>,
    pub command_mode: String,
    pub dictionary_mode: String,
    pub command_ids_json: String,
    pub dictionary_entry_ids_json: String,
    pub enabled: bool,
    pub priority: i32,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for WindowContext {
    type Module = super::RemoteModule;
}
