// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::window_context_type::WindowContext;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `window_context`.
///
/// Obtain a handle from the [`WindowContextTableAccess::window_context`] method on [`super::RemoteTables`],
/// like `ctx.db.window_context()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.window_context().on_insert(...)`.
pub struct WindowContextTableHandle<'ctx> {
    imp: __sdk::TableHandle<WindowContext>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `window_context`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WindowContextTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WindowContextTableHandle`], which mediates access to the table `window_context`.
    fn window_context(&self) -> WindowContextTableHandle<'_>;
}

impl WindowContextTableAccess for super::RemoteTables {
    fn window_context(&self) -> WindowContextTableHandle<'_> {
        WindowContextTableHandle {
            imp: self.imp.get_table::<WindowContext>("window_context"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WindowContextInsertCallbackId(__sdk::CallbackId);
pub struct WindowContextDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WindowContextTableHandle<'ctx> {
    type Row = WindowContext;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WindowContext> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WindowContextInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WindowContextInsertCallbackId {
        WindowContextInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WindowContextInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WindowContextDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WindowContextDeleteCallbackId {
        WindowContextDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WindowContextDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WindowContext>("window_context");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct WindowContextUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WindowContextTableHandle<'ctx> {
    type UpdateCallbackId = WindowContextUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WindowContextUpdateCallbackId {
        WindowContextUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WindowContextUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<WindowContext>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WindowContext>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `window_context`,
/// which allows point queries on the field of the same name
/// via the [`WindowContextIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.window_context().id().find(...)`.
pub struct WindowContextIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WindowContext, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WindowContextTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `window_context`.
    pub fn id(&self) -> WindowContextIdUnique<'ctx> {
        WindowContextIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WindowContextIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<WindowContext> {
        self.imp.find(col_val)
    }
}
